spring:
  application:
    name: fis-training-test-02
  datasource:
    url: jdbc:mysql://localhost:3306/fis-training?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: haku1404
  jpa:
    show-sql: true
    generate-ddl: true